/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StatisticGUI;

import DTO.doanhthuDTO;
import java.util.ArrayList;
import org.jfree.data.category.DefaultCategoryDataset;
import BUS.doanhthuBUS;
import java.awt.Color;
import java.awt.Font;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;

/**
 *
 * @author Bon Nguyen
 */
public class ThongKeDT_LoiNhuanBarChart extends javax.swing.JPanel {
    ArrayList<doanhthuDTO> ds_ln_chart;
    Font font = new Font("Segoe UI", Font.PLAIN, 15);
    doanhthuBUS doanhthuBUS;
    /**
     * Creates new form ThongKeDT_LoiNhuanBarChart
     */
    public ThongKeDT_LoiNhuanBarChart() {
        initComponents();
        doanhthuBUS = new doanhthuBUS();
        ds_ln_chart = new ArrayList<>();
        ds_ln_chart = doanhthuBUS.GetList_DTTQ();
        int s=0;
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        for(doanhthuDTO dtln:ds_ln_chart){
            if(s<5){
                int q = dtln.getQuarter();
                String a = Integer.toString(q);
                double ln = dtln.getTienlai();
                data.setValue(ln, "Doanh thu","Quý " + a);
                s++;
            }
        }
        
        JFreeChart chart = ChartFactory.createBarChart("Doanh thu theo quý", "", "Doanh thu", data, PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.white);
        chart.getTitle().setPaint(Color.black);
        chart.getTitle().setFont(font);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.red);
        
        // Lấy đối tượng NumberAxis của trục y và thiết lập định dạng số
        NumberAxis yAxis = (NumberAxis) p.getRangeAxis();
        yAxis.setNumberFormatOverride(java.text.NumberFormat.getInstance());     
        CategoryAxis domainAxis = p.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setSize(507, 420);
        
        pannelDTLN.add(chartPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannelDTLN = new javax.swing.JPanel();

        javax.swing.GroupLayout pannelDTLNLayout = new javax.swing.GroupLayout(pannelDTLN);
        pannelDTLN.setLayout(pannelDTLNLayout);
        pannelDTLNLayout.setHorizontalGroup(
            pannelDTLNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        pannelDTLNLayout.setVerticalGroup(
            pannelDTLNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelDTLN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelDTLN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pannelDTLN;
    // End of variables declaration//GEN-END:variables
}
