/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StatisticGUI;

import DTO.customerDTO;
import Model.CustomHeaderRenderer;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import BUS.banhangBUS;
import DTO.doanhthuDTO;
import Model.CustomTableCellRenderer;
import Model.NonEditableTableModel;
import static Model.helpers.convertBackgroundOfTable;
import static Model.helpers.formatMoney;
import static Model.helpers.*;
import javax.swing.JTable;
import Model.MyScrollBar;
/**
 *
 * @author Bon Nguyen
 */
public class ThongKeBH_KhachHangTable extends javax.swing.JPanel {
    DefaultTableModel model;
    ArrayList<customerDTO> ds_bhkh = new ArrayList<>();    
    /**
     * Creates new form ThongKeBH_KhachHang
     */
    public ThongKeBH_KhachHangTable() {
        initComponents();
        jScrollPane1.setVerticalScrollBar(new MyScrollBar());
        JTableHeader header = tblBHKH.getTableHeader();
        header.setDefaultRenderer(new CustomHeaderRenderer());
        banhangBUS banhangBUS = new banhangBUS();
        ds_bhkh = banhangBUS.Get_ListBHKH();
        System.out.println(ds_bhkh);
        banhangBUS.viewData(tblBHKH, ds_bhkh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBHKH = new javax.swing.JTable();

        tblBHKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBHKH);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTable_BHKH(){
        return tblBHKH;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBHKH;
    // End of variables declaration//GEN-END:variables
}
