/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StatisticGUI;

import BUS.customerBUS;
import BUS.doanhthuBUS;
import BUS.productBUS;
import BUS.receptBUS;
import BUS.staffBUS;
import DTO.doanhthuDTO;
import Model.MyMessageAlert;
import static Model.helpers.Compare_Date;
import static Model.helpers.Convert_date;
import java.awt.event.ItemEvent;
import java.io.File;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import static Model.helpers.*;

/**
 *
 * @author Bon Nguyen
 */
public class ThongKe extends javax.swing.JPanel {

    int selected;
    JFrame parentFrame;
    productBUS productBUS;
    customerBUS customerBUS;
    receptBUS receptBUS;
    staffBUS staffBUS;
    doanhthuBUS doanhthuBUS;
    ThongKeDT_SanPhamTable DT_SP;
    ThongKeDT_SanPhamBarChart DT_SP_Chart;
    ThongKeDT_TheoNgayTable DT_TN;
    ThongKeDT_TheoNgayBarChart DT_TN_Chart;
    ThongKeDT_LoiNhuanTable DT_TQ;
    ThongKeDT_LoiNhuanBarChart DT_TQ_Chart;
    ThongKeBH_KhachHangTable BH_KH;
    ThongKeBH_KhachHangBarChart BH_KH_Chart;
    private ArrayList<doanhthuDTO> ds_DTSP = new ArrayList<>();

    JTable table_dtsp;
    JTable table_dttn;
    JTable table_bhkh;
    int flag = 0;
    //Lấy đường dẫn tới file
    File file = new File("");
    String currentDirectory = file.getAbsolutePath();
    String relativePath = currentDirectory + "\\src\\main\\java\\IMG\\"; // Đường dẫn tương đối

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        selected = -1;
        parentFrame = new JFrame();
        productBUS productBUS = new productBUS();
        customerBUS customerBUS = new customerBUS();
        receptBUS receptBUS = new receptBUS();
        staffBUS staffBUS = new staffBUS();
        File image_cus = new File(relativePath + "user.png");
        // Tạo một ImageIcon từ một File
        ImageIcon cus = new ImageIcon(image_cus.getAbsolutePath());
        // Thiết lập biểu tượng cho JLabel
        lblcus.setIcon(cus);

        File image_profit = new File(relativePath + "profits.png");
        // Tạo một ImageIcon từ một File
        ImageIcon profit = new ImageIcon(image_profit.getAbsolutePath());
        // Thiết lập biểu tượng cho JLabel
        lblProfit.setIcon(profit);

        File image_product = new File(relativePath + "product.png");
        // Tạo một ImageIcon từ một File
        ImageIcon product = new ImageIcon(image_product.getAbsolutePath());
        // Thiết lập biểu tượng cho JLabel
        lblProduct.setIcon(product);

        File image_receipt = new File(relativePath + "bill.png");
        // Tạo một ImageIcon từ một File
        ImageIcon receipt = new ImageIcon(image_receipt.getAbsolutePath());
        // Thiết lập biểu tượng cho JLabel
        lblReceipt.setIcon(receipt);

//        int s = productBUS.TotalProduct();
        //    lblNBProduct.setText(""+s);
        int t = customerBUS.TotalCustomer();
        lblNBCus.setText("" + t);

        int f = receptBUS.Get_SLHD();
        lblNBReceipt.setText("" + f);

        int b = staffBUS.Get_SLNV();
        lblNBStf.setText("" + b);

        cbMethod.setLabeText("Chọn hình thức");
        cbType.setLabeText("Chọn dạng");
        cbMethod.addItem("Doanh thu");
        cbMethod.addItem("Bán hàng");

        OnOff(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblProfit = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        lblNBStf = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblProduct = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        lblNBProduct = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pannelChart = new javax.swing.JPanel();
        pannelTable = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblReceipt = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        lblNBReceipt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblcus = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        lblNBCus = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DateStart = new com.toedter.calendar.JDateChooser();
        cbMethod = new Model.Combobox();
        txtDateStart = new javax.swing.JLabel();
        DateEnd = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txtDateEnd = new javax.swing.JLabel();
        cbType = new Model.Combobox();
        jLabel5 = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thống kê");

        jPanel9.setBackground(new java.awt.Color(66, 100, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 120));

        text1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setText("Tổng số nhân viên");

        lblNBStf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNBStf.setForeground(new java.awt.Color(255, 255, 255));
        lblNBStf.setText("10");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(lblNBStf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(text1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNBStf)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(204, 153, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 120));

        text2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setText("Sản phẩm hiện có");

        lblNBProduct.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNBProduct.setForeground(new java.awt.Color(255, 255, 255));
        lblNBProduct.setText("23");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(text2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lblNBProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(text2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNBProduct)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pannelChart.setBackground(new java.awt.Color(255, 255, 255));
        pannelChart.setPreferredSize(new java.awt.Dimension(513, 420));

        javax.swing.GroupLayout pannelChartLayout = new javax.swing.GroupLayout(pannelChart);
        pannelChart.setLayout(pannelChartLayout);
        pannelChartLayout.setHorizontalGroup(
            pannelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pannelChartLayout.setVerticalGroup(
            pannelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        pannelTable.setBackground(new java.awt.Color(255, 255, 255));
        pannelTable.setPreferredSize(new java.awt.Dimension(426, 420));
        pannelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelTableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pannelTableLayout = new javax.swing.GroupLayout(pannelTable);
        pannelTable.setLayout(pannelTableLayout);
        pannelTableLayout.setHorizontalGroup(
            pannelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        pannelTableLayout.setVerticalGroup(
            pannelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pannelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelChart, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pannelChart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(pannelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(0, 204, 102));
        jPanel12.setPreferredSize(new java.awt.Dimension(220, 120));

        text3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 255, 255));
        text3.setText("Tổng số đơn hàng");

        lblNBReceipt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNBReceipt.setForeground(new java.awt.Color(255, 255, 255));
        lblNBReceipt.setText("1500");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(text3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(lblNBReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(text3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNBReceipt)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 120));

        text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setText("Tổng số khách hàng");

        lblNBCus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNBCus.setForeground(new java.awt.Color(255, 255, 255));
        lblNBCus.setText("10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNBCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNBCus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(248, 248, 248));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Chọn ");

        DateStart.setDateFormatString("yyyy-MM-dd");
        DateStart.setPreferredSize(new java.awt.Dimension(200, 42));

        cbMethod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMethodItemStateChanged(evt);
            }
        });
        cbMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMethodActionPerformed(evt);
            }
        });

        txtDateStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateStart.setText("Ngày bắt đầu");

        DateEnd.setDateFormatString("yyyy-MM-dd");
        DateEnd.setPreferredSize(new java.awt.Dimension(188, 42));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.setPreferredSize(new java.awt.Dimension(97, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtDateEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateEnd.setText("Ngày kết thúc");

        cbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTypeItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Hình thức");

        btnShow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShow.setText("Xác nhận");
        btnShow.setPreferredSize(new java.awt.Dimension(97, 23));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(DateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnExportExcel.setBackground(new java.awt.Color(51, 204, 0));
        btnExportExcel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExportExcel.setForeground(new java.awt.Color(255, 255, 255));
        btnExportExcel.setText("Xuất Excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExportExcel)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void OnOff(boolean a) {
        DateStart.show(a);
        DateEnd.show(a);
        txtDateStart.show(a);
        txtDateEnd.show(a);
    }

    public void Method() {
        Object selectedItem = cbMethod.getSelectedItem();
        if (selectedItem != null) {
            if (selectedItem.equals("Doanh thu")) {
                cbType.addItem("Sản phẩm");
                cbType.addItem("Khoảng thời gian");
                cbType.addItem("Theo quý");
            } else if (selectedItem.equals("Bán hàng")) {
                cbType.addItem("Khách hàng");
            }
        } else {

        }
    }

    public void CheckDate() {
        if (DateStart.getDate() == null || DateEnd.getDate() == null) {
            MyMessageAlert alert = new MyMessageAlert(parentFrame, "Vui lòng chọn đầy đủ ngày");
            alert.setVisible(true);
            return;
        }
    }

    public Date getDateStartChooser() throws ParseException {
        return Convert_date(DateStart.getDate());
    }

    public Date getDateEndChooser() throws ParseException {
        return Convert_date(DateEnd.getDate());
    }

    public void Show_DT() throws ParseException {
        if (cbMethod.getSelectedItem() != null && cbType.getSelectedItem() != null) {
            if (cbMethod.getSelectedItem().equals("Doanh thu") && cbType.getSelectedItem().equals("Sản phẩm")) {
                pannelTable.removeAll();
                DT_SP = new ThongKeDT_SanPhamTable();
                DT_SP.setSize(426, 416);
                pannelTable.add(DT_SP);
                pannelTable.updateUI();
                System.out.print("OK");
                flag = 1;
                table_dtsp = DT_SP.getTable();

                pannelChart.removeAll();
                DT_SP_Chart = new ThongKeDT_SanPhamBarChart();
                DT_SP_Chart.setSize(507, 416);
                pannelChart.add(DT_SP_Chart);
                pannelChart.updateUI();
            }

            if (cbMethod.getSelectedItem().equals("Doanh thu") && cbType.getSelectedItem().equals("Khoảng thời gian")) {
                CheckDate();
                if (!Compare_Date(DateStart.getDate(), DateEnd.getDate())) {
                    MyMessageAlert alert = new MyMessageAlert(parentFrame, "Ngày chọn không hợp lệ");
                    alert.setVisible(true);
                    return;
                } else {
                    pannelTable.removeAll();
                    DT_TN = new ThongKeDT_TheoNgayTable(getDateStartChooser(), getDateEndChooser());
                    DT_TN.setSize(426, 416);
                    pannelTable.add(DT_TN);
                    pannelTable.updateUI();
                    flag = 2;
                    table_dttn = DT_TN.getList_DTTN();

                    pannelChart.removeAll();
                    DT_TN_Chart = new ThongKeDT_TheoNgayBarChart(getDateStartChooser(), getDateEndChooser());
                    DT_TN_Chart.setSize(507, 416);
                    pannelChart.add(DT_TN_Chart);
                    pannelChart.updateUI();
                }
            }

            if (cbMethod.getSelectedItem().equals("Bán hàng") && cbType.getSelectedItem().equals("Khách hàng")) {
                pannelTable.removeAll();
                BH_KH = new ThongKeBH_KhachHangTable();
                BH_KH.setSize(426, 416);
                pannelTable.add(BH_KH);
                pannelTable.updateUI();
                flag = 2;
                table_bhkh = BH_KH.getTable_BHKH();

                pannelChart.removeAll();
                BH_KH_Chart = new ThongKeBH_KhachHangBarChart();
                BH_KH_Chart.setSize(507, 416);
                pannelChart.add(BH_KH_Chart);
                pannelChart.updateUI();
            }

            if (cbMethod.getSelectedItem().equals("Doanh thu") && cbType.getSelectedItem().equals("Theo quý")) {
                pannelTable.removeAll();
                DT_TQ = new ThongKeDT_LoiNhuanTable();
                DT_TQ.setSize(426, 416);
                DT_TQ.setVisible(true);
                pannelTable.add(DT_TQ);
                pannelTable.updateUI();

                pannelChart.removeAll();
                DT_TQ_Chart = new ThongKeDT_LoiNhuanBarChart();
                DT_TQ_Chart.setSize(513, 416);
                DT_TQ_Chart.setVisible(true);
                pannelChart.add(DT_TQ_Chart);
                pannelChart.updateUI();
            }

        } else {
            MyMessageAlert alert = new MyMessageAlert(parentFrame, "Vui lòng chọn đầy đủ");
            alert.setVisible(true);
        }
    }

    public void printExcel() {
        if (flag == 1) {
            Export_Excell(table_dtsp);
        }
        if (flag == 2) {
            Export_Excell(table_dttn);
        }
        if (flag == 3) {
            Export_Excell(table_bhkh);
        }
    }

    private void pannelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelTableMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_pannelTableMouseClicked

    private void cbMethodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMethodItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            cbType.removeAllItems();
            Method();
        }
    }//GEN-LAST:event_cbMethodItemStateChanged

    private void cbMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMethodActionPerformed

    }//GEN-LAST:event_cbMethodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTypeItemStateChanged
        if (cbType.getSelectedItem() != null) {
            if (cbType.getSelectedItem().equals("Khoảng thời gian")) {
                OnOff(true);
            } else {
                OnOff(false);
            }
        }
    }//GEN-LAST:event_cbTypeItemStateChanged

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        if (cbMethod.getSelectedItem() != null) {
            try {
                Show_DT();
            } catch (ParseException ex) {
                Logger.getLogger(ThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        printExcel();
    }//GEN-LAST:event_btnExportExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateEnd;
    private com.toedter.calendar.JDateChooser DateStart;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnShow;
    private Model.Combobox cbMethod;
    private Model.Combobox cbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblNBCus;
    private javax.swing.JLabel lblNBProduct;
    private javax.swing.JLabel lblNBReceipt;
    private javax.swing.JLabel lblNBStf;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProfit;
    private javax.swing.JLabel lblReceipt;
    private javax.swing.JLabel lblcus;
    private javax.swing.JPanel pannelChart;
    private javax.swing.JPanel pannelTable;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel txtDateEnd;
    private javax.swing.JLabel txtDateStart;
    // End of variables declaration//GEN-END:variables
}
