package GUI.StatisticGUI;

import DTO.doanhthuDTO;
import Model.CustomHeaderRenderer;
import Model.NonEditableTableModel;
import static Model.helpers.convertBackgroundOfTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import static Model.helpers.*;
import java.util.ArrayList;
import BUS.doanhthuBUS;
import java.awt.Font;
import Model.CustomTableCellRenderer;
import static Model.helpers.*;
import javax.swing.JTable;
import Model.MyScrollBar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Bon Nguyen
 */
public class ThongKeDT_SanPhamTable extends javax.swing.JPanel {

    DefaultTableModel model;
    doanhthuBUS doanhthuBUS;
    Font font = new Font("Segoe UI", Font.PLAIN, 14);
    private ArrayList<doanhthuDTO> ds_dtsp = new ArrayList<>();

    /**
     * Creates new form ThongKeDT_SanPhamTable
     */
    public ThongKeDT_SanPhamTable() {
        initComponents();
        jScrollPane1.setVerticalScrollBar(new MyScrollBar());
        doanhthuBUS doanhthuBUS = new doanhthuBUS();
        JTableHeader header = tblDTSP.getTableHeader();
        header.setDefaultRenderer(new CustomHeaderRenderer());
        ds_dtsp = doanhthuBUS.getList_DTSP();
        viewData(tblDTSP, ds_dtsp);

    }

    public void addLine(doanhthuDTO dt_sp) {
        model.addRow(new Object[]{
            dt_sp.getProductName(), dt_sp.getSLBan(), formatMoney(ConvertDoubleToInt(dt_sp.getTiensauKM())) + "đ"
        });
    }

    public void viewData(JTable tblDTSP, ArrayList<doanhthuDTO> list) {
        int s = 0;
        convertBackgroundOfTable(tblDTSP);
        String[] headers = {"Tên sản phẩm", "Số lượng bán", "Doanh thu"}; // Đặt tiêu đề cột của bảng
        model = new NonEditableTableModel(new Object[0][headers.length], headers);
        tblDTSP.setModel(model);
        tblDTSP.setRowHeight(30);
        tblDTSP.setFont(font);

        CustomTableCellRenderer centerRenderer = new CustomTableCellRenderer();
        tblDTSP.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblDTSP.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

        removeData();
        for (doanhthuDTO dt_sp : list) {
            addLine(dt_sp);
            s += dt_sp.getTiensauKM();
        }
        model.addRow(new Object[]{
            "", "Tổng", formatMoney(s) + "đ"
        });
    }

    public void removeData() {
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    public JTable getTable() {
        return tblDTSP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDTSP = new javax.swing.JTable();

        tblDTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDTSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDTSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDTSP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDTSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDTSPMouseClicked

    }//GEN-LAST:event_tblDTSPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDTSP;
    // End of variables declaration//GEN-END:variables
}
