/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StatisticGUI;

import BUS.doanhthuBUS;
import DTO.doanhthuDTO;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Bon Nguyen
 */
public class ThongKeDT_SanPhamBarChart extends javax.swing.JPanel {
    Font font = new Font("Segoe UI", Font.PLAIN, 15); 
    private ArrayList<doanhthuDTO> dt_sp_chart;
    doanhthuBUS doanhthuBUS;
    /**
     * Creates new form ThongKeDT_SanPhamBarChart
     */
    public ThongKeDT_SanPhamBarChart() {
        initComponents();
        doanhthuBUS doanhthuBUS = new doanhthuBUS();
        dt_sp_chart = doanhthuBUS.getList_DTSP_Chart();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (doanhthuDTO dtsp : dt_sp_chart) {
            String productName = dtsp.getProductName();
            double revenue = dtsp.getTiensauKM();
            dataset.setValue(revenue, "Doanh thu", productName);
        }
        
        JFreeChart chart = ChartFactory.createBarChart("Top 5 sản phẩm có doanh số cao", "", "Doanh thu", dataset, PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.white);
        chart.getTitle().setPaint(Color.black);
        chart.getTitle().setFont(font);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.red);
        
        // Lấy đối tượng NumberAxis của trục y và thiết lập định dạng số
        NumberAxis yAxis = (NumberAxis) p.getRangeAxis();
        yAxis.setNumberFormatOverride(java.text.NumberFormat.getInstance());     
        CategoryAxis domainAxis = p.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setSize(507, 420);
        
        pannelDTSP.add(chartPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannelDTSP = new javax.swing.JPanel();

        pannelDTSP.setPreferredSize(new java.awt.Dimension(513, 420));

        javax.swing.GroupLayout pannelDTSPLayout = new javax.swing.GroupLayout(pannelDTSP);
        pannelDTSP.setLayout(pannelDTSPLayout);
        pannelDTSPLayout.setHorizontalGroup(
            pannelDTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        pannelDTSPLayout.setVerticalGroup(
            pannelDTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelDTSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelDTSP, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("pannelDTSP");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pannelDTSP;
    // End of variables declaration//GEN-END:variables
}
