/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.manageraccount;

import javax.swing.JButton;
import BUS.staffBUS;
import DTO.staffDTO;
import GUI.managerproduct.detail;
import Model.CustomHeaderRenderer;
import Model.NonEditableTableModel;
import static Model.helpers.ConvertDoubleToInt;
import static Model.helpers.convertBackgroundOfTable;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class choosestaffid extends javax.swing.JPanel {
    private staffBUS stbus = new staffBUS();
    private DefaultTableModel model;
    private adduser addUserPanel;
//    choosestaffid chooseStaffId = new choosestaffid();
    public JButton getDong() {
        return dong;
    }
     public void setAddUserPanel(adduser addUserPanel) {
          this.addUserPanel = addUserPanel;
    }
    public choosestaffid() {
        initComponents();
        JTableHeader header = table.getTableHeader();
        header.setDefaultRenderer(new CustomHeaderRenderer());
        convertBackgroundOfTable(table);
        String[] headers = {"staffID", "firstName", "lastName", "gender", "phoneNumber", "address", "salary", "role", "yearOfBirth"};

        model = new NonEditableTableModel(new Object[0][headers.length], headers);
        table.setModel(model);
        table.setRowHeight(40);
        displayData();

//       table.addMouseListener(new MouseAdapter() {
//    @Override
//    public void mouseClicked(MouseEvent e) {
//        if (e.getClickCount() == 2) {
//            int selectedRow = table.getSelectedRow();
//            if (selectedRow != -1) {
//                String staffID = table.getValueAt(selectedRow, 0).toString();
//                adduser addus = (adduser) SwingUtilities.getAncestorOfClass(adduser.class, choosestaffid.this);
//                addus.setjTextField1(staffID);
//                SwingUtilities.getWindowAncestor(choosestaffid.this).dispose();
//            }
//        }
//    }
//});
   }

   

    private void displayData() {
        ArrayList<staffDTO> list = stbus.getList();
        model.setRowCount(0);
        for (staffDTO staff : list) {
            Object[] row = {
                staff.getStaffID(),
                staff.getFirstname(),
                staff.getLastname(),
                staff.getGender(),
                staff.getPhonenumber(),
                staff.getAddress(),
                ConvertDoubleToInt(staff.getSalary()),
                staff.getRole(),
                staff.getYearofbirth()
            };
            model.addRow(row);
        }
    
    table.setModel(model);
    
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        dong = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "StaffID", "FirstName", "LastName", "Gender", "NumberPhone", "Address", "salary", "role", "YearOfBirth", "Img"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(66, 100, 220));

        dong.setBackground(new java.awt.Color(255, 102, 102));
        dong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dong.setText("Đóng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
         
        try {
            adduser us = new adduser();
       
        if (evt.getClickCount() == 2) {
            int selectedRow = table.getSelectedRow();
            if (selectedRow != -1) {
                Object value = table.getValueAt(selectedRow, 0);
               if (addUserPanel != null) {
                     String textValue = value.toString();
                     addUserPanel.setjTextField1(textValue);
        // Sử dụng textValue theo nhu cầu của bạn
    }
                SwingUtilities.getWindowAncestor(choosestaffid.this).dispose();
            }
        }
         } catch (SQLException ex) {
            Logger.getLogger(choosestaffid.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dong;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
