/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.SellGUI;
import DTO.productDTO;
import BUS.productBUS;
import DTO.table_receiptDTO;
import static Model.helpers.ConvertDoubleToInt;
//import Model.CustomHeaderRenderer;
//import Model.CustomTableCellRenderer;
import static Model.helpers.convertBackgroundOfTable;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
/**
 *
 * @author MY PC
 * 
 * 
 */

public class chonSP extends javax.swing.JFrame {

    /**
     * Creates new form chonSP
     */
     private ArrayList<productDTO> list = new ArrayList<>();
     private ArrayList<productDTO> listsp = new ArrayList<>();
     public static int pos =0;
      productBUS productBUS;
      private int sl =1;
      DefaultTableModel model;
      DefaultTableModel model1;
      //TableModel model;
      TableModel model2;
      sell _testsell;
  
      productDTO x;
      
      public chonSP()
      {
          initComponents();
      }
    public chonSP(sell testsell) {
        initComponents();
         setLocationRelativeTo(null);
         
        this.productBUS = new productBUS();
        list = productBUS.getList();
        _testsell=testsell;
//        CustomTableCellRenderer cellRenderer = new CustomTableCellRenderer();
//        tblSP.setDefaultRenderer(Object.class, cellRenderer);
        JTableHeader header = tblSP.getTableHeader();
        header.setFont(new Font("Tahoma", Font.BOLD, 16)); // Font in đậm
        header.setResizingAllowed(false);
       // header.setDefaultRenderer(new CustomHeaderRenderer());
        //JTableHeader header1 = tblSP.getTableHeader();
       // header1.setDefaultRenderer(new CustomHeaderRenderer());
        ViewData(list);
       
        
        
        
    }
    public void ViewData(ArrayList<productDTO> list)
    {
        convertBackgroundOfTable(tblSP);
        String[] header = {"Mã sản phẩm ","Hãng","Tên sản phẩm","Giá"};
        model = (DefaultTableModel) 
        tblSP.getModel();
        model.setColumnIdentifiers(header);
        tblSP.getColumnModel().getColumn(0).setPreferredWidth(90);
        tblSP.getColumnModel().getColumn(1).setPreferredWidth(90);
        tblSP.getColumnModel().getColumn(2).setPreferredWidth(110);
        tblSP.getColumnModel().getColumn(3).setPreferredWidth(90);
        removeData();
        
        for(productDTO product:list)
        {
             addData(product);
            
        }
       
    }
//    public void addList(ArrayList<productDTO> listsp){
//         for(productDTO product:listsp)
//        {
//             addData1(product);
//            
//        }
//        
//    }
    public void addData(productDTO product)
    {
        model.addRow(new Object[]{
            product.getProducctID(), product.getBrandID(),product.getProductName(),ConvertDoubleToInt(product.getUnitPrice())
        });
    }
//     public void addData1(productDTO product)
//    {
//        model1.addRow(new Object[]{
//            product.getProducctID(), product.getBrandID(),product.getProductName(),sl,productBUS.ConvertDoubleToInt(product.getUnitPrice())
//        });
//    }
    public void removeData()
    {
        int count = model.getRowCount();
        for(int i= count-1;i>=0;i--)
        {
            model.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 380));

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblSP.setRowHeight(40);
        tblSP.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblSP.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblSP.setShowGrid(true);
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSP);

        btnBack.setBackground(new java.awt.Color(73, 36, 62));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Quay về");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnChon.setBackground(new java.awt.Color(45, 67, 86));
        btnChon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChon.setForeground(new java.awt.Color(255, 255, 255));
        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Chọn sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {                                   

         
    }                                  
  
    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:


        TableModel model2 = tblSP.getModel();
       //int [] select = tblSP.getSelectedRows();
       
         Object [] newFormRow = new Object[5];
           
                int check = 0;
                int choose = tblSP.getSelectedRow();
               // Object [] newFormRows = new Object[5];
                newFormRow[0] = model2.getValueAt(choose,0);
                // Object id = model2.getValueAt(choose,0);
                //String id = id.toString();
             //  form.txtid.setText(id);
                for(int row = 0; row<_testsell.model.getRowCount();row++)
           {
               Object id = _testsell.model.getValueAt(row, 0);
//            //   String productid = id.toString();
                  if( newFormRow[0].equals(id))
             {
                 Object s= _testsell.model.getValueAt(row, 3);
                 int quantity= (int)s;
                  quantity = quantity +1;
                  newFormRow[1] = model2.getValueAt(choose,1);
                  newFormRow[2] = model2.getValueAt(choose,2);
                  newFormRow[3] = quantity ;
                 newFormRow[4] = model2.getValueAt(choose,3);                 
                 _testsell.model.setValueAt(quantity , row, 3);        
                 check = 1;
             }
               
              }
           
           // newFormRow[0] = model2.getValueAt(select[i],0);
           if(check == 0)
           {
                newFormRow[1] = model2.getValueAt(choose,1);
                newFormRow[2] = model2.getValueAt(choose,2);
                newFormRow[3] = sl;
                newFormRow[4] = model2.getValueAt(choose,3);    
                _testsell.model.addRow(newFormRow);  
           }
               
       


               
                
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.hide();
        _testsell.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

//GEN-FIRST:event_tblSPMouseClicked
 
//GEN-LAST:event_tblSPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chonSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chonSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chonSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chonSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chonSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblSP;
    // End of variables declaration//GEN-END:variables
}
