/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.manageraccount.manageraccount;
import GUI.managerproduct.managerproduct;
import GUI.DoiThongTinGUI;
import GUI.ImportGUI.TaoPhieuNhapGUI;
import GUI.LoginGUI.Login;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Model.CustomConfirmDialog;
import GUI.PromotionGUI.KhuyenMaiGUI;
import GUI.SellGUI.sell;
import GUI.customer.customerGUI;
import GUI.employee.employeeGUI;
import GUI.SellGUI.sell;
import GUI.SellGUI.showkm;
import GUI.StatisticGUI.ThongKe;
import GUI.SupplierGUI.NhaCungCapGUI;
import GUI.ReceiptGUI.HoaDonGUI;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author khoan
 */
public class MainGUI extends javax.swing.JFrame {

    private sell sell;
    private showkm showkm;
    private employeeGUI nhanvien;
    private customerGUI nguoidung;
    private TaoPhieuNhapGUI taophieunhap;
    private NhaCungCapGUI nhacungcap;
    private showkm showkm;
    //Lấy đường dẫn tới file
    File file = new File("");
    String currentDirectory = file.getAbsolutePath();
    String relativePath = currentDirectory + "\\src\\main\\java\\IMG\\"; // Đường dẫn tương đối
    /**
     * Creates new form MainForm
     */

    //Mở panel riêng
    private KhuyenMaiGUI khuyenmai;

    private manageraccount MNaccount;
    private managerproduct MNproduct;

    private ThongKe thongke;
    private HoaDonGUI hoadon;

    public String id, name, role;

    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MainGUI(String id, String name, String role) {
        this.id = id;
        this.name = name;
        this.role = role;
        initComponents();
        setLocationRelativeTo(null);

        //User Sign
        File image_logo = new File(relativePath + "Employee.png");
        // Tạo một ImageIcon từ một File
        ImageIcon icon = new ImageIcon(image_logo.getAbsolutePath());
        // Thiết lập biểu tượng cho JLabel
        lblLogo.setIcon(icon);

        File image_exit = new File(relativePath + "exit.png");
        ImageIcon icon_exit = new ImageIcon(image_exit.getAbsolutePath());
        lblExit.setIcon(icon_exit);

        lblName.setText(name);
        lblRole.setText(role);
        Open_GUI(1);

        if (role.equals("staff")) {
            Role_OnOff(true, false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pannelBH = new javax.swing.JPanel();
        lblBanhang = new javax.swing.JLabel();
        pannelSP = new javax.swing.JPanel();
        lblSanpham = new javax.swing.JLabel();
        pannelNCC = new javax.swing.JPanel();
        lblNhacungcap = new javax.swing.JLabel();
        pannelKH = new javax.swing.JPanel();
        lblConnguoi = new javax.swing.JLabel();
        pannelHD = new javax.swing.JPanel();
        lblHoadon = new javax.swing.JLabel();
        pannelTK = new javax.swing.JPanel();
        lblTaikhoan = new javax.swing.JLabel();
        pannelThK = new javax.swing.JPanel();
        lblThongke = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        pannelNV = new javax.swing.JPanel();
        lblNhanvien = new javax.swing.JLabel();
        pannelKM = new javax.swing.JPanel();
        lblKhuyenmai = new javax.swing.JLabel();
        pannelNH = new javax.swing.JPanel();
        lblNhaphang = new javax.swing.JLabel();
        lblDoithongtin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jmain = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(244, 700));

        pannelBH.setBackground(new java.awt.Color(0, 51, 204));
        pannelBH.setPreferredSize(new java.awt.Dimension(0, 40));
        pannelBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelBHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pannelBHMouseEntered(evt);
            }
        });

        lblBanhang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblBanhang.setForeground(new java.awt.Color(255, 255, 255));
        lblBanhang.setText("Bán hàng");

        javax.swing.GroupLayout pannelBHLayout = new javax.swing.GroupLayout(pannelBH);
        pannelBH.setLayout(pannelBHLayout);
        pannelBHLayout.setHorizontalGroup(
            pannelBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelBHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelBHLayout.setVerticalGroup(
            pannelBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBanhang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelSP.setBackground(new java.awt.Color(255, 255, 255));
        pannelSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pannelSPMouseEntered(evt);
            }
        });

        lblSanpham.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblSanpham.setText("Sản phẩm");

        javax.swing.GroupLayout pannelSPLayout = new javax.swing.GroupLayout(pannelSP);
        pannelSP.setLayout(pannelSPLayout);
        pannelSPLayout.setHorizontalGroup(
            pannelSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelSPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelSPLayout.setVerticalGroup(
            pannelSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelNCC.setBackground(new java.awt.Color(255, 255, 255));
        pannelNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelNCCMouseClicked(evt);
            }
        });

        lblNhacungcap.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNhacungcap.setText("Nhà cung cấp");

        javax.swing.GroupLayout pannelNCCLayout = new javax.swing.GroupLayout(pannelNCC);
        pannelNCC.setLayout(pannelNCCLayout);
        pannelNCCLayout.setHorizontalGroup(
            pannelNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelNCCLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelNCCLayout.setVerticalGroup(
            pannelNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhacungcap, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelKH.setBackground(new java.awt.Color(255, 255, 255));
        pannelKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pannelKHMouseEntered(evt);
            }
        });

        lblConnguoi.setBackground(new java.awt.Color(255, 255, 255));
        lblConnguoi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblConnguoi.setText("Khách hàng");

        javax.swing.GroupLayout pannelKHLayout = new javax.swing.GroupLayout(pannelKH);
        pannelKH.setLayout(pannelKHLayout);
        pannelKHLayout.setHorizontalGroup(
            pannelKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelKHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblConnguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelKHLayout.setVerticalGroup(
            pannelKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConnguoi, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelHD.setBackground(new java.awt.Color(255, 255, 255));
        pannelHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelHDMouseClicked(evt);
            }
        });

        lblHoadon.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblHoadon.setText("Hóa đơn");

        javax.swing.GroupLayout pannelHDLayout = new javax.swing.GroupLayout(pannelHD);
        pannelHD.setLayout(pannelHDLayout);
        pannelHDLayout.setHorizontalGroup(
            pannelHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelHDLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelHDLayout.setVerticalGroup(
            pannelHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelTK.setBackground(new java.awt.Color(255, 255, 255));
        pannelTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelTKMouseClicked(evt);
            }
        });

        lblTaikhoan.setBackground(new java.awt.Color(255, 255, 255));
        lblTaikhoan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTaikhoan.setText("Tài khoản");

        javax.swing.GroupLayout pannelTKLayout = new javax.swing.GroupLayout(pannelTK);
        pannelTK.setLayout(pannelTKLayout);
        pannelTKLayout.setHorizontalGroup(
            pannelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelTKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelTKLayout.setVerticalGroup(
            pannelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelThK.setBackground(new java.awt.Color(255, 255, 255));
        pannelThK.setPreferredSize(new java.awt.Dimension(200, 40));
        pannelThK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelThKMouseClicked(evt);
            }
        });

        lblThongke.setBackground(new java.awt.Color(255, 255, 255));
        lblThongke.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblThongke.setText("Thống kê");

        javax.swing.GroupLayout pannelThKLayout = new javax.swing.GroupLayout(pannelThK);
        pannelThK.setLayout(pannelThKLayout);
        pannelThKLayout.setHorizontalGroup(
            pannelThKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelThKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelThKLayout.setVerticalGroup(
            pannelThKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongke, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(66, 100, 240));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(66, 100, 220));
        jPanel13.setPreferredSize(new java.awt.Dimension(135, 40));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pannelNV.setBackground(new java.awt.Color(255, 255, 255));
        pannelNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelNVMouseClicked(evt);
            }
        });

        lblNhanvien.setBackground(new java.awt.Color(255, 255, 255));
        lblNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNhanvien.setText("Nhân viên");

        javax.swing.GroupLayout pannelNVLayout = new javax.swing.GroupLayout(pannelNV);
        pannelNV.setLayout(pannelNVLayout);
        pannelNVLayout.setHorizontalGroup(
            pannelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelNVLayout.setVerticalGroup(
            pannelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelKM.setBackground(new java.awt.Color(255, 255, 255));
        pannelKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelKMMouseClicked(evt);
            }
        });

        lblKhuyenmai.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblKhuyenmai.setText("Khuyến mãi");

        javax.swing.GroupLayout pannelKMLayout = new javax.swing.GroupLayout(pannelKM);
        pannelKM.setLayout(pannelKMLayout);
        pannelKMLayout.setHorizontalGroup(
            pannelKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelKMLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelKMLayout.setVerticalGroup(
            pannelKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhuyenmai, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pannelNH.setBackground(new java.awt.Color(255, 255, 255));
        pannelNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelNHMouseClicked(evt);
            }
        });

        lblNhaphang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNhaphang.setText("Nhập hàng");

        javax.swing.GroupLayout pannelNHLayout = new javax.swing.GroupLayout(pannelNH);
        pannelNH.setLayout(pannelNHLayout);
        pannelNHLayout.setHorizontalGroup(
            pannelNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelNHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pannelNHLayout.setVerticalGroup(
            pannelNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhaphang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lblDoithongtin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDoithongtin.setText("Đổi thông tin tài khoản");
        lblDoithongtin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDoithongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoithongtinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoithongtinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoithongtinMouseExited(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLogout.setText("Đăng xuất");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelBH, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
            .addComponent(pannelSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pannelKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pannelHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addComponent(pannelNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(pannelNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pannelKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pannelNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pannelTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pannelThK, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblDoithongtin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pannelBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelThK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoithongtin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(950, 700));

        jPanel1.setBackground(new java.awt.Color(66, 100, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 40));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setPreferredSize(new java.awt.Dimension(35, 35));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setPreferredSize(new java.awt.Dimension(35, 35));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setPreferredSize(new java.awt.Dimension(110, 16));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setPreferredSize(new java.awt.Dimension(110, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jmain.setBackground(new java.awt.Color(255, 102, 0));
        jmain.setPreferredSize(new java.awt.Dimension(950, 650));

        javax.swing.GroupLayout jmainLayout = new javax.swing.GroupLayout(jmain);
        jmain.setLayout(jmainLayout);
        jmainLayout.setHorizontalGroup(
            jmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jmainLayout.setVerticalGroup(
            jmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Computer Store Software");
        jLabel3.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        CustomConfirmDialog confirm = new CustomConfirmDialog(this, "Xác nhận thoát", "Bạn có muốn thoát?", "close_red.png");
        confirm.setVisible(true);
        if (confirm.getSelected()) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        File image_exit_hover = new File(relativePath + "exit_hover.png");
        ImageIcon icon_exit_hover = new ImageIcon(image_exit_hover.getAbsolutePath());
        lblExit.setIcon(icon_exit_hover);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        File image_exit = new File(relativePath + "exit.png");
        ImageIcon icon_exit = new ImageIcon(image_exit.getAbsolutePath());
        lblExit.setIcon(icon_exit);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblDoithongtinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoithongtinMouseEntered
        lblDoithongtin.setForeground(Color.red);
    }//GEN-LAST:event_lblDoithongtinMouseEntered

    private void lblDoithongtinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoithongtinMouseExited
        lblDoithongtin.setForeground(Color.black);
    }//GEN-LAST:event_lblDoithongtinMouseExited

    private void Role_OnOff(boolean a, boolean b) {
        //nhân viên
        pannelBH.show(a);
        pannelSP.show(a);
        pannelKH.show(a);
        pannelNCC.show(a);
        pannelKM.show(a);

        //admin và quản lý
        pannelHD.show(b);
        pannelNV.show(b);
        pannelTK.show(b);
        pannelThK.show(b);
        pannelNH.show(b);
    }

    private void set_color_pannel(int a) {
        pannelBH.setBackground(new java.awt.Color(255, 255, 255));
        pannelSP.setBackground(new java.awt.Color(255, 255, 255));
        pannelNCC.setBackground(new java.awt.Color(255, 255, 255));
        pannelKH.setBackground(new java.awt.Color(255, 255, 255));
        pannelHD.setBackground(new java.awt.Color(255, 255, 255));
        pannelTK.setBackground(new java.awt.Color(255, 255, 255));
        pannelThK.setBackground(new java.awt.Color(255, 255, 255));
        pannelNV.setBackground(new java.awt.Color(255, 255, 255));
        pannelNH.setBackground(new java.awt.Color(255, 255, 255));
        pannelKM.setBackground(new java.awt.Color(255, 255, 255));

        lblSanpham.setForeground(new java.awt.Color(0, 0, 0));
        lblBanhang.setForeground(new java.awt.Color(0, 0, 0));
        lblConnguoi.setForeground(new java.awt.Color(0, 0, 0));
        lblNhacungcap.setForeground(new java.awt.Color(0, 0, 0));
        lblNhaphang.setForeground(new java.awt.Color(0, 0, 0));
        lblHoadon.setForeground(new java.awt.Color(0, 0, 0));
        lblKhuyenmai.setForeground(new java.awt.Color(0, 0, 0));
        lblNhanvien.setForeground(new java.awt.Color(0, 0, 0));
        lblTaikhoan.setForeground(new java.awt.Color(0, 0, 0));
        lblThongke.setForeground(new java.awt.Color(0, 0, 0));

        switch (a) {
            case 1:
                pannelBH.setBackground(new java.awt.Color(0, 51, 204));
                lblBanhang.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 2:
                pannelSP.setBackground(new java.awt.Color(0, 51, 204));
                lblSanpham.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 3:
                pannelNCC.setBackground(new java.awt.Color(0, 51, 204));
                lblNhacungcap.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 4:
                pannelKH.setBackground(new java.awt.Color(0, 51, 204));
                lblConnguoi.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 5:
                pannelHD.setBackground(new java.awt.Color(0, 51, 204));
                lblHoadon.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 6:
                pannelTK.setBackground(new java.awt.Color(0, 51, 204));
                lblTaikhoan.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 7:
                pannelThK.setBackground(new java.awt.Color(0, 51, 204));
                lblThongke.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 8:
                pannelNV.setBackground(new java.awt.Color(0, 51, 204));
                lblNhanvien.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 9:
                pannelNH.setBackground(new java.awt.Color(0, 51, 204));
                lblNhaphang.setForeground(new java.awt.Color(255, 255, 255));
                break;
            case 10:
                pannelKM.setBackground(new java.awt.Color(0, 51, 204));
                lblKhuyenmai.setForeground(new java.awt.Color(255, 255, 255));
                break;
        }

    }

    private void Open_GUI(int a) {
        switch (a) {
            case 1:
//                lblBanhang.setEnabled(true);
                jmain.removeAll();
                sell = new sell(this);
                sell.setSize(950, 650);
                jmain.add(sell);
                jmain.updateUI();
                break;


            case 4:
                lblConnguoi.setEnabled(true);
                jmain.removeAll();
                nguoidung = new customerGUI();
                nguoidung.setSize(950,650);
                jmain.add(nguoidung);
                jmain.updateUI();
                break;
            case 8:
                lblNhanvien.setEnabled(true);
                jmain.removeAll();
                nhanvien = new employeeGUI();
                nhanvien.setSize(950,650);
                jmain.add(nhanvien);
            case 2:
                MNproduct = new managerproduct();
                MNproduct.setEnabled(true);
                jmain.removeAll();
                MNproduct.setSize(950, 650);
                jmain.add(MNproduct);
                jmain.updateUI();
                break;
            // case 4:

//                lblConnguoi.setEnabled(true);
//                jmain.removeAll();
//                nguoidung = new customerGUI();
//                nguoidung.setSize(950,650);
//                jmain.add(nguoidung);
//                jmain.updateUI();
//                break;
            case 3:
                this.lblNhacungcap.setEnabled(true);
                jmain.removeAll();
                nhacungcap = new NhaCungCapGUI();
                nhacungcap.setSize(950, 650);
                jmain.add(nhacungcap);
                jmain.updateUI();
                break;
//              case 8:
//                lblNhanvien.setEnabled(true);
//                jmain.removeAll();
//                nhanvien = new employeeGUI();
//                nhanvien.setSize(950,650);
//                jmain.add(nhanvien);
//                jmain.updateUI();
//                break;
            //  case 8:
//                lblNhanvien.setEnabled(true);
//                jmain.removeAll();
//                nhanvien = new employeeGUI();
//                nhanvien.setSize(950,650);
//                jmain.add(nhanvien);
//                jmain.updateUI();
//                break;

            case 5:
                lblHoadon.setEnabled(true);
                jmain.removeAll();
                 {
                    try {
                        hoadon = new HoaDonGUI();
                    } catch (ParseException ex) {
                        Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                hoadon.setSize(950, 650);
                jmain.add(hoadon);
                jmain.updateUI();
                break;

            case 6:
                MNaccount = new manageraccount();
                MNaccount.setEnabled(true);
                jmain.removeAll();
                MNaccount.setSize(950, 650);
                jmain.add(MNaccount.getContentPane());
                jmain.updateUI();
                break;

            case 7:
                lblThongke.setEnabled(true);
                jmain.removeAll();
                thongke = new ThongKe();
                thongke.setSize(950, 650);
                jmain.add(thongke);
                jmain.updateUI();
                break;

            case 8:
                lblNhanvien.setEnabled(true);
                jmain.removeAll();
                nhanvien = new employeeGUI();
                nhanvien.setSize(950, 650);
                jmain.add(nhanvien);
                jmain.updateUI();
                break;

            case 9:
                this.lblNhaphang.setEnabled(true);
                jmain.removeAll();
                taophieunhap = new TaoPhieuNhapGUI(this);
                taophieunhap.setSize(950, 650);
                jmain.add(taophieunhap);
                jmain.updateUI();
                break;

            case 10:
                lblKhuyenmai.setEnabled(true);
                jmain.removeAll();
                khuyenmai = new KhuyenMaiGUI(role);
                khuyenmai.setSize(950, 650);
                jmain.add(khuyenmai);
                jmain.updateUI();
                break;
        }
    }
    private void pannelBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelBHMouseClicked
        set_color_pannel(1);
        Open_GUI(1);
    }//GEN-LAST:event_pannelBHMouseClicked

    private void pannelSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelSPMouseClicked
        set_color_pannel(2);
        Open_GUI(2);
    }//GEN-LAST:event_pannelSPMouseClicked

    private void pannelKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelKHMouseClicked
        set_color_pannel(4);
        Open_GUI(4);
    }//GEN-LAST:event_pannelKHMouseClicked

    private void pannelNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelNCCMouseClicked
        set_color_pannel(3);
        Open_GUI(3);
    }//GEN-LAST:event_pannelNCCMouseClicked

    private void pannelNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelNHMouseClicked
        set_color_pannel(9);
        Open_GUI(9);
    }//GEN-LAST:event_pannelNHMouseClicked

    private void pannelHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelHDMouseClicked
        set_color_pannel(5);
        Open_GUI(5);
    }//GEN-LAST:event_pannelHDMouseClicked

    private void pannelKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelKMMouseClicked
        set_color_pannel(10);
        Open_GUI(10);
    }//GEN-LAST:event_pannelKMMouseClicked

    private void pannelNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelNVMouseClicked
        set_color_pannel(8);
        Open_GUI(8);
    }//GEN-LAST:event_pannelNVMouseClicked

    private void pannelTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelTKMouseClicked
        set_color_pannel(6);
        Open_GUI(6);
    }//GEN-LAST:event_pannelTKMouseClicked

    private void pannelThKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelThKMouseClicked
        set_color_pannel(7);
        Open_GUI(7);
    }//GEN-LAST:event_pannelThKMouseClicked

    private void pannelSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelSPMouseEntered

    }//GEN-LAST:event_pannelSPMouseEntered

    private void pannelKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelKHMouseEntered

    }//GEN-LAST:event_pannelKHMouseEntered

    private void pannelBHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelBHMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pannelBHMouseEntered

    private void lblDoithongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoithongtinMouseClicked
        DoiThongTinGUI changeinfo = new DoiThongTinGUI(id);
        changeinfo.setVisible(true);
    }//GEN-LAST:event_lblDoithongtinMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(Color.red);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setForeground(Color.black);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        File image_exit = new File(relativePath + "exit.png");
        ImageIcon icon_exit = new ImageIcon(image_exit.getAbsolutePath());
        lblExit.setIcon(icon_exit);
        CustomConfirmDialog logout = new CustomConfirmDialog(this, "Xác nhận đăng xuất", "Bạn có muốn đăng xuất?", "close_red.png");
        logout.setVisible(true);
        if (logout.getSelected()) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jmain;
    private javax.swing.JLabel lblBanhang;
    private javax.swing.JLabel lblConnguoi;
    private javax.swing.JLabel lblDoithongtin;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHoadon;
    private javax.swing.JLabel lblKhuyenmai;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNhacungcap;
    private javax.swing.JLabel lblNhanvien;
    private javax.swing.JLabel lblNhaphang;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSanpham;
    private javax.swing.JLabel lblTaikhoan;
    private javax.swing.JLabel lblThongke;
    private javax.swing.JPanel pannelBH;
    private javax.swing.JPanel pannelHD;
    private javax.swing.JPanel pannelKH;
    private javax.swing.JPanel pannelKM;
    private javax.swing.JPanel pannelNCC;
    private javax.swing.JPanel pannelNH;
    private javax.swing.JPanel pannelNV;
    private javax.swing.JPanel pannelSP;
    private javax.swing.JPanel pannelTK;
    private javax.swing.JPanel pannelThK;
    // End of variables declaration//GEN-END:variables
}
